name: Karsajobs Image Build & Push

on:
  push:
    branches: [ "karsajobs" ]
  pull_request:
    branches: [ "karsajobs" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: karsajobs

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Node
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          verbose: true
      
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Node
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.15

      - name: Display Go version
        run: go version

      - name: Start test
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build & Push Image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
