name: Karsajobs-ui Image Build & Push

on:
  push:
    branches: [ "karsajobs-ui" ]
  pull_request:
    branches: [ "karsajobs-ui" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: karsajobs-ui


jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Node
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          verbose: true
          
  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Node
        uses: actions/checkout@v3
        
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build & Push Image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest